apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springapp-argo-application
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-deployment-channel
spec:
  project: default

  source:
    repoURL: https://github.com/mertcakmak2/spring-k8s-argocd.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-argocd-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true